language: java

install:
  - sudo pip install requests[security]
  - sudo pip install coveralls

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6

after_success:
  - mvn clean test jacoco:report coveralls:report
